### ISSUE TITLE
Is there any way to remove headers from iframe?

### ISSUE THREAD

**Issue by PedroFumero** [sunneydev/requests#1]
Hello, I hope you're doing well. Excuse me, I'd like to insert some websites inside my app. But I'd like to remove these headers: 'x-frame-options', 'content-security-policy' at the moment of getting the response in my iframe.

I mean, the request is not triggered from a fetch action, it's triggered by an iFrame, how could I use this package to be able to remove those headers from the response?

**Comment by sxnney** [comment]
Hi @PedroFumero, I believe those headers are added by your browser and can not be interfered or overridden.

**Comment by PedroFumero** [comment]
Hello @sunneydev, those headers are added by the server that sends the response. I've successfully removed them using some Chrome extensions, but I need a simpler solution for our customers. No problem, thanks anyway.

**Comment by sxnney** [comment]
> Hello @sunneydev, those headers are added by the server that sends the response. I've successfully removed them using some Chrome extensions, but I need a simpler solution for our customers. No problem, thanks anyway.

I see, I guess it can only be removed with extensions API's.
